Esri/jsapi-resources

bower/README.md, bower/dojo/package.json, bower/requirejs/Gruntfile.js, bower/requirejs/package.json
work in progress to resolve #18
* fixed a few typos and added package.json descriptions
* removed `private` tags (let me know if you meant to keep those)
* implemented @odoe's suggestion in the RequireJS `Gruntfile.js` (~~not~~ working ~~*yet*~~)
to do:
> i see now that including built.html and copying it into the `dist`folder as `index.html` on the fly is what allows developers to debug the raw source and create their production `.html` purely using build tools.  i'll see if i can find a way to clarify that in the doc.
=> remove raw .css from built RequireJS sample

3.x/bower/dojo/package.json, 3.x/bower/requirejs/package.json, 4.x/bower/requirejs/package.json
i believe this resolves #22.  not following @dbened-denver-water's suggestion to a *t*, but rather following the convention in the `4.x` directory:
https://github.com/Esri/jsapi-resources/blob/master/4.x/bower/dojo/package.json#L7
=> update 3.x dojo project path in package.json

4.x/typescript/demo/tsconfig.json
this (temporary) tweak hooks up intellisense and automatic recompile via [`atom-typescript`](https://atom.io/packages/atom-typescript) too.
reference:
https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#declaration-packages-types-are-not-loaded.
=> make sure typescript demo is plug and play in Atom too

frameworks/README.md, frameworks/angular-1/README.md, frameworks/angular/README.md, frameworks/ember/README.md, frameworks/react/README.md
First pass at a set of pages to link out to tools and examples of how to use the ArcGIS API for JavaScript with various frameworks. These pages are meant to compliment the framework examples in the [samples pages](https://developers.arcgis.com/javascript/latest/sample-code/index.html). The examples linked to here show how to use the ArcGIS API in applications that use the conventions and tooling typical of each framework (something we can't do in the sample pages).
You can view this live here:
https://github.com/tomwayson/jsapi-resources/tree/frameworks/frameworks
=> Frameworks

CONTRIBUTING.md, README.md
addresses #71 
i like the idea of putting the information directly in the README and just linking to Esri's generic boilerplate CONTRIBUTING doc.
=> mention additional resources in README

frameworks/angular/README.md
Point to esri-loader instead since angular-esri-loader has been deprecated.
=> Replace link to deprecated angular-esri-loader

4.x/webpack/demo/package.json
Updated dependency versions to fix node-sass related build issue, described below.
I am reporting an issue with
OS: Windows 10
Running NPM install results in an error related to node-sass.
First, it tries to download a file from Github, which does not exist.
```console
> node-sass@4.8.1 install C:\Users\jacobsj\Documents\GitHub\jsapi-resources\4.x\webpack\demo\node_modules\node-sass
> node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.8.1/win32-x64-64_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.8.1/win32-x64-64_binding.node":
HTTP error 404 Not Found
```
Then it tries to build the file that it couldn't download, but fails because I don't have Windows SDK version 8.1 installed.
```console
> …
```
=> fixes node-sass related build issue

3.x/bower/dojo/bower.json
Using the HTTPS url instead of the `git@` is the only url structure that works for me, and AFAIK it's generally more compatible for more users.
=> bower file - clone with https

4.x/typescript/demo/index.html
This regex works better for me in cases that we're at the root (website.com) OR at a subdirectory (website.com/demo/). This is the regex used in https://dojotoolkit.org/documentation/tutorials/1.10/hello_dojo.
=> TypeScript demo: update dojo app regex to work with more url scenarios

4.x/npm/demo/package.json
When upgrading from 4.13->4.15, ran into an issue with a missing dependency, dojo-util, that used to be a transitive dependency of arcgis-js-api.
According to https://developers.arcgis.com/javascript/latest/guide/using-npm/index.html#build-dojo
> When creating dojo builds, you will need to install the dojo utilities in your project.
> npm install --save-dev Esri/dojo-util#v1.14.2/esri-3.28.0
Build was able to successfully complete after installing dojo-util as a dev-dependency.
=> Add dojo-util dev dependency

3.x/typescript/arcgis-js-api.d.ts
The existing namespace is listed as "sri" rather than "esri".
=> Fixes a typo in the module definition for PlayerZoomBehaviors

esm-samples/webpack/package-lock.json, esm-samples/webpack/package.json, esm-samples/webpack/webpack.config.js
This PR adds an additional `file-loader` rule for css assets.
This only seems to be required for Windows, as the `@arcgis/webpack-plugin` handles most of these, but could be some conflict in nested deps.
=> fix #235, need loaders for assets

esm-samples/README.md
Add info on when to use config.assetsPath. I also opened an issue for the SDK at 4.19. I figured having this info in multiple places is the best approach since we've gotten a number of questions about it.
=> esm-samples - add info to README about config.assetsPath

esm-samples/README.md, esm-samples/jsapi-angular-cli/README.md, esm-samples/jsapi-angular-cli/src/app/app.component.ts, esm-samples/jsapi-create-react-app/README.md, esm-samples/jsapi-create-react-app/src/App.js, esm-samples/jsapi-ember-cli/README.md, esm-samples/jsapi-ember-cli/app/components/map.js, esm-samples/jsapi-node/README.md, esm-samples/jsapi-node/src/projection.js, esm-samples/jsapi-vue-cli/README.md, esm-samples/jsapi-vue-cli/src/App.vue, esm-samples/rollup/README.md, esm-samples/rollup/src/main.js, esm-samples/webpack/README.md, esm-samples/webpack/src/index.js
Document setting config.assetsPath. This will be required at 4.19.
Implement consistent naming convention for the default export: `esriConfig`
=> Update ESM samples to set assetsPath

esm-samples/jsapi-vue-cli/package.json
This PR fixes an issue with HMR not working in the `/esm-samples/jsapi-vue-cli` sample.
* Updated @vue/cli and related plugins
* Refactored npm scripts
* Removed unused dependencies
* Fixed WDS (webpack development server) disconnecting problems.
=> Update jsapi-vue-cli sample

esm-samples/jsapi-vue-cli/package.json
Accidentally left virtual host. Switching back to `localhost`.
=> Vue sample - update hostname.

esm-samples/webpack/package.json, esm-samples/webpack/webpack.config.js
Replace `CleanWebpackPlugin` with `output.clean = true;`. This is an updated approach in Webpack 5 that also removes the additional plugin dependency.
Reference: https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder
=> Webpack sample - replace CleanWebpackPlugin

4.x/typescript/README.md, 4.x/webpack/demo/README.md, esm-samples/jsapi-angular-cli/README.md
This adds temporary notices about current limitations in TypeScript when using it with autocasting. It's mainly aimed at devs who are copying API samples or code snippets, since many of them use autocasting.
Also includes other minor touchups in the READMEs.
=> Add note about using TypeScript with autocasting.

4.x/webpack/README.md, README.md
This adds a deprecation notice to the 4.x/webpack/README. We now recommend using ES modules.
=> AMD webpack sample deprecation notice.

esm-samples/rollup/rollup.config.js
Reference #327. This will speed up the dev builds.
With some quick testing on my 2018 Mac, using this repos rollup sample my dev build times improved from approx. 14 seconds to approx. 9 seconds (about 35% improvement).
cc @gavinr
=> Update rollup dev build config to disable treeshaking.

esm-samples/webpack/README.md, esm-samples/webpack/package.json, esm-samples/webpack/src/index.css, esm-samples/webpack/webpack.config.js
Had to make a change in the webpack config due to a [breaking change](https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#-breaking-changes-4).
> the contentBase, contentBasePublicPath, serveIndex, staticOptions, watchContentBase, watchOptions were removed in favor of the static option
=> bump webpack to 4.21

esm-samples/jsapi-angular-cli/README.md, esm-samples/jsapi-angular-cli/package.json, esm-samples/jsapi-angular-cli/src/app/app.component.css, esm-samples/jsapi-create-react-app/README.md, esm-samples/jsapi-create-react-app/package.json, esm-samples/jsapi-create-react-app/src/index.css, esm-samples/jsapi-custom-workers/README.md, esm-samples/jsapi-custom-workers/package.json, esm-samples/jsapi-custom-workers/public/index.html, esm-samples/jsapi-custom-workers/src/index.css, esm-samples/jsapi-custom-workers/src/index.js, esm-samples/jsapi-custom-workers/webpack.config.js, esm-samples/jsapi-ember-cli/README.md, esm-samples/jsapi-esm-cdn/esm-cdn.html, esm-samples/jsapi-node/README.md, esm-samples/jsapi-node/package.json, esm-samples/jsapi-vue-cli/.eslintrc, esm-samples/jsapi-vue-cli/README.md, esm-samples/jsapi-vue-cli/package.json, esm-samples/jsapi-vue-cli/public/index.html, esm-samples/jsapi-vue-cli/src/App.vue, esm-samples/jsapi-vue-cli/src/main.css, esm-samples/jsapi-vue-cli/vue.config.js, esm-samples/rollup/README.md, esm-samples/rollup/package.json, esm-samples/rollup/public/index.html, esm-samples/webpack/README.md, esm-samples/webpack/package.json, esm-samples/webpack/src/index.css, esm-samples/webpack/webpack.config.js
Update all esm samples to 4.21.
Notable items:
* Added notice to ember sample that it will no longer be maintained
* Added additional configuration to Vue sample to allow for production build testing
* Added note to Angular sample about browser caching when updating dependencies
* Minor modification to custom workers sample to delay running worker until button is clicked
* Replaced webpack.config's `devServer.contentBase` with `static` in two samples
=> 4.21 release

esm-samples/rollup/README.md, esm-samples/rollup/rollup.config.js, esm-samples/rollup/rollup.config.prod.js
As an alternative to a new example; see https://github.com/Esri/jsapi-resources/pull/363#issuecomment-1006839387
=> Add instructions to convert rollup example to TypeScript

esm-samples/jsapi-create-react-app/package.json
This PR updates the React sample's production browserslist to match the one used in the Angular sample. This will reduce both the initial load size and on-disk footprint. I left the dev browserslist alone, it's still using the CRA defaults.
=> Update React sample browserslist

esm-samples/jsapi-create-react-app/src/App.js, esm-samples/rollup/src/main.js, esm-samples/webpack/src/index.js
Use the same jsapi code as the React, etc. samples for a one-to-one build size comparison.
=> refactor(webpack, rollup): standardize jsapi code in esm samples

.github/workflows/analyze-builds.yml
Skips the metrics workflow run on PRs with the draft label. Samples are bumped ahead of time before the release occurs, so this will prevent the workflow from failing.
=> ci(metrics): skip workflow run on prs with draft label 

.github/scripts/build-size.js
Pretty hacky, but it was easier than hardcoding. When you add the performance sizes, make sure to:
- put "size" in the property name
- return the values in bytes (this is better in general because it maintains the precision and lets the user decide how they want to format the sizes)
I can hardcode the size conversion for each size property if you think this is unmaintainable. Otherwise I'll doc this weird workflow.
=> ci(metrics): convert csv output sizes to megabytes

3.x/bower/dojo/build.profile.js, 3.x/bower/dojo/package.json, esm-samples/.metrics/4.23.0.csv
Had to add some more folders to the `trees` to ignore in the Dojo build. The build throws a single random closure `JSC_SUSPICIOUS_SEMICOLON` warning, but treats it as an error, so had to add `--force` to the script. No runtime errors, but everything works.
=> 3x bower: update moment trees

.github/workflows/analyze-builds.yml
Prevents the script from running when `package.json` files are changed in `3.x/...` such as #406
=> ci(metrics): only run when package.json files are changed in esm-samples

esm-samples/.metrics/4.23.0.csv, esm-samples/jsapi-create-react-app/README.md, esm-samples/jsapi-create-react-app/package.json
Updating the readme with the browserlist [currently in `package.json`](https://github.com/Esri/jsapi-resources/blob/master/esm-samples/jsapi-create-react-app/package.json#L27-L41).
=> docs(react): update browserlist in readme

esm-samples/jsapi-create-react-app/README.md, esm-samples/jsapi-create-react-app/package.json, esm-samples/jsapi-create-react-app/src/index.css, esm-samples/jsapi-node/package.json, esm-samples/jsapi-vue/README.md, esm-samples/jsapi-vue/package.json, esm-samples/jsapi-vue/src/main.css, esm-samples/rollup/README.md, esm-samples/rollup/package.json, esm-samples/rollup/public/index.html, esm-samples/webpack/README.md, esm-samples/webpack/package.json, esm-samples/webpack/src/index.css
Bumping the react, vue, webpack, rollup, and node samples for the 4.24 release
=> build(deps): bump samples to 4.24

esm-samples/webpack/README.md
This adds a new Known Issue note in the Webpack sample README. It provides information and a potential fix for users encountering unexpected token errors when using Webpack 4 with JS API v4.24+.
=> Add known issue about Webpack 4 and unexpected token errors

esm-samples/webpack/README.md
Adds one small, but important, update to the wording in PR: https://github.com/Esri/jsapi-resources/pull/427
=> Add mention about needing an appropriate loader to the Known Issue

esm-samples/.metrics/4.25.0.csv, esm-samples/jsapi-custom-widget/README.md, esm-samples/jsapi-custom-widget/package.json, esm-samples/jsapi-custom-widget/src/widget.tsx, esm-samples/jsapi-custom-widget/tsconfig.json
Includes the following updates for the Custom Widget sample:
- bumps sample to Vite 3
- add `"useDefineForClassFields": false` to tsconfig
- add Known Issue note about `useDefineForClassFields` setting is now required
- added handles to watcher
- add Deprecation Notice
cc @dasa @hgonzago
=> Update custom widget sample

.github/workflows/analyze-builds.yml
Fix github action errors like this one:
`error: The following untracked working tree files would be overwritten by merge: esm-samples/.metrics/4.25.0.csv`
It also includes a fix for the `set-output` deprecation.
@benelan can you double check the fix(es) we chatted about it? Thanks!
=> Fix github action csv merge overwrite error

esm-samples/.metrics/4.25.0.csv, esm-samples/jsapi-custom-workers/README.md, esm-samples/jsapi-custom-workers/package.json, esm-samples/jsapi-custom-workers/src/index.css, esm-samples/rollup/README.md, esm-samples/rollup/package.json, esm-samples/webpack/public/index.html
Updated jsapi-custom-workers and rollup samples. Primary reason was to upgrade `@rollup/plugin-terser` to `v0.4.0` for performance reasons. 
Also updated the webpack sample's `index.html` to include a viewport meta tag.
=> Small update rollup samples

esm-samples/.metrics/4.25.0.csv, esm-samples/rollup/README.md, esm-samples/rollup/package.json, esm-samples/rollup/rollup.config.prod.js
This update significantly reduces the number of http requests on initial load.
=> Update rollup sample to 3.14.0

.github/scripts/build-perf.js, esm-samples/.metrics/4.26.5.csv, esm-samples/jsapi-angular-cli/package.json, esm-samples/jsapi-custom-widget/package.json, esm-samples/jsapi-custom-workers/package.json, esm-samples/jsapi-node/package.json, esm-samples/jsapi-react/package.json, esm-samples/jsapi-vue/package.json, esm-samples/rollup/package.json, esm-samples/webpack/package.json
The ESM build stats were incorrectly reporting the `totalJSRequests` metric. This number represents the total number of JavaScript files requests by each sample that is tested. A bug was preventing the value from resetting to zero between tests, which resulted in the number being calculated cumulatively. 
This fix applies to all new updates going forward. At this time, it does not update test results for previous versions. 
Reference: https://github.com/Esri/jsapi-resources/tree/main/esm-samples/.metrics
=> Fix reporting of totalJSRequests in ESM build stats

esm-samples/.metrics/4.26.5.csv, esm-samples/jsapi-node/README.md, esm-samples/jsapi-node/native-esm/request.mjs, esm-samples/jsapi-node/native-esm/webmap.mjs, esm-samples/jsapi-node/package.json, esm-samples/jsapi-node/test-request.js, esm-samples/jsapi-node/test-webmap.js
Remove polyfills from `jsapi-node` sample and update README:
- `cross-fetch` appears to be unmaintained.
- `abort-controller` is supported as of Node 15.0.
- `fetch` is included in Node 18
cc @odoe
=> Node.js sample - remove polyfills

4.x/typescript/README.md, 4.x/typescript/demo/README.md, 4.x/typescript/demo/index.html, 4.x/typescript/demo/package.json, 4.x/typescript/demo/tsconfig.json
Made the following updates to the demo app:
- Switched from using NPM installed type defs to using the local `.d.ts` file in the `4.x/TypeScript` directory
- Removed `arcgis-js-api` and `@types/arcgis-js-api` from the dependencies
- Added some clarification wording in the READMEs
- Scaled down the tsconfig
- Updated sample to use CDN version 4.27
- Added license info
- Updated TS version to 5.x
=> chore(sample): various updates to the AMD TS demo app

esm-samples/jsapi-node/README.md
* Clarify node version(s) needed to run the sample. 
* Add Known Issue for `fetch` when using node versions < 18
=> chore(jsapi-node): update README

esm-samples/jsapi-angular-cli/.browserslistrc
Override Angular's default browerslist to suppress warning message that showed up at Angular 15. We've added and removed this list over time, and now it's back again.
```
One or more browsers which are configured in the project's Browserslist configuration will be ignored as ES5 output is not supported by the Angular CLI.
Ignored browsers: bb 10, bb 7, ie 11, ie 10, ie_mob 11, ie_mob 10, kaios 2.5, op_mini all
```
References: https://angular.io/guide/build#configuring-browser-compatibility. 
/cc @odoe
=> chore(angular): add browserslistrc

esm-samples/.metrics/4.28.0.csv, esm-samples/jsapi-custom-ui/package.json, esm-samples/jsapi-react/package.json, esm-samples/jsapi-vite-ts/package.json, esm-samples/jsapi-vue/package.json
This PR updates:
- jsapi-custom-ui
- jsapi-react
- jsapi-vite-ts
- jsapi-vue
/cc @odoe
=> chore: update vite samples to v5

esm-samples/.metrics/4.28.0.csv, esm-samples/jsapi-angular-cli/README.md, esm-samples/jsapi-angular-cli/package.json
Notable items:
* Enable esbuild for dev work (significantly faster!)
* Update the Known Issue verbiage for using webpack for production, and add a new link to angular.dev for better info on the builders options.
=> chore(angular): various updates

esm-samples/webpack/webpack.config.js
Changed the devServer port from 3001 to 8080 to avoid conflicts on Windows.
Reference: https://webpack.js.org/configuration/dev-server/#devserverport
=> chore(webpack): update devServer.port

esm-samples/esbuild/src/index.js, esm-samples/jsapi-angular-cli/src/app/app.component.ts, esm-samples/jsapi-custom-ui/src/App.jsx, esm-samples/jsapi-esm-cdn/esm-cdn.html, esm-samples/jsapi-react/src/App.jsx, esm-samples/jsapi-vite-ts/src/main.ts, esm-samples/jsapi-vue/src/App.vue, esm-samples/rollup/src/main.js, esm-samples/webpack/src/index.js
Remove the `Bookmarks.editingEnabled` property from samples.
=> chore(Bookmarks): remove deprecated property

esm-samples/esbuild/src/index.js, esm-samples/jsapi-angular-cli/src/app/app.component.ts, esm-samples/jsapi-custom-ui/src/App.jsx, esm-samples/jsapi-esm-cdn/esm-cdn.html, esm-samples/jsapi-react/src/App.jsx, esm-samples/jsapi-vite-ts/src/main.ts, esm-samples/jsapi-vue/src/App.vue, esm-samples/rollup/src/main.js, esm-samples/webpack/src/index.js
For samples using `aa1d3f80270146208328cf66d022e09c` switch to using `70b726074af04a7e9839d8a07f64c039`.
=> chore: update webmap

.github/workflows/analyze-builds.yml
* Modify the samples git diff to look for changes on the branch since the version before the last commit. Previously it was comparing against origin/main. This may have caused an accidental recursion in the github action, under certain circumstances.
* Also fix bug in one of the sample paths.
=> chore(GHA): update git diff on samples directories

.github/scripts/create-zips.js
The create-zip.js script currently only works by zipping subdirectories. This enhancement accommodates stand alone samples. 
@dasa can you review?
```
// Current behavior is limited to subdirectory-only zipping
/component-samples/map-components/samples/ 
/component-samples/map-components/samples/angular
/component-samples/map-components/samples/cdn
. . .  
```
This enhancement provides the capability to zip all individual files plus subdirectories:
```
/component-samples/disconnected-environment/
/component-samples/disconnected-environment/index.html
/component-samples/disconnected-environment/public/
/component-samples/disconnected-environment/.gitignore
. . .
```
/cc @omarkawach
=> fix(GHA): update zip-create to accommodate stand-alone component samples
