3.x/typescript/arcgis-js-api.d.ts

Update `3.x/typescript/arcgis-js-api.d.ts` for v3.17

Update for ArcGIS API for JavaScript version 3.17

---

4.x/bower/requirejs/Gruntfile.js

There are a few errors with the referenced files on a fresh pull/build. These changes allow the build to go through successfully, although I'm not 100% certain it's the correct change to make!

Fix build errors.

---

3.x/typescript/README.md
4.x/typescript/README.md

Use npm instead of typings to install arcgis-js-api.d.ts file

---

4.x/typescript/demo/README.md
4.x/typescript/demo/package.json

* resolved npm install nags
* added a little more info/context to the install steps
* fixed compile error reported in #52

resolves #52, more ts demo clarity

---

4.x/typescript/demo/app/main.ts

Updating `main.ts` typescript example to not have TypeScript compilation errors.
#77

Modified to remove typescript errors

---

frameworks/react/README.md

I'm getting rid of my custom domain soon so this reverts back to the github url. For now it will redirect to the custom domain until it expires

update demo urls

---

frameworks/ember/README.md

Add links to all the open source Ember addons maintained by Esri

Add ember-esri-loader and ember-arcgis-* addons

---

frameworks/angular-1/README.md
frameworks/angular/README.md
frameworks/ember/README.md
frameworks/react/README.md

As I agreed with [Tom](https://github.com/Esri/jsapi-resources/issues/112#issuecomment-356086179) ^_^.

Adding links to additional resources #112

---

frameworks/vue/README.md

add framework page for Vue.js

---

frameworks/react/README.md

update react framework page w/ libraries, examples, and presentations

---

frameworks/README.md
frameworks/angular-1/README.md
frameworks/angular/README.md

Minor updates for DevSummit to include new Angular CLI sample repo https://github.com/Esri/angular-cli-esri-map

Doc update

---

.github/ISSUE_TEMPLATE.md
frameworks/ember/README.md

add issue template

---

frameworks/angular/README.md

Added 2018 Dev Summit Angular slides info.

Update Angular README.md

---

frameworks/angular/README.md

As per suggestion by @RalucaNicola

Remove outdated examples

---

frameworks/angular/README.md
frameworks/react/README.md
frameworks/vue/README.md

add links to @arcgis/webpack-plugin

---

frameworks/angular/README.md

@odoe or @tomwayson simple fix of a broken link. Can you pls review and merge?

Updated angular sample broken link to use stackblitz

---

4.x/typescript/demo/app/main.ts
4.x/typescript/demo/index.html
4.x/typescript/demo/package.json
4.x/typescript/demo/tsconfig.json

on https://developers.arcgis.com/javascript/latest/guide/typescript-setup/index.html

Update to 4.11 / Changes to fit the doc 

---

4.x/typescript/demo/package-lock.json
4.x/typescript/demo/package.json
4.x/typescript/demo/tsconfig.json

TS demo updates. 
* Bump JS API version to 4.17.0
* Remove `importHelpers` from tsconfig.json
cc @hgonzago

Update TS demo

---

esm-samples/jsapi-angular-cli/src/app/app.component.ts

Some small changes to fix TSLint warnings and improve code quality/consistency per this project's "tslint.json" file:
- Use single quotes (Rule: quotemark)
- Add missing semicolons (Rule: semicolon)
- End file "app.component.ts" with new line (Rule: eofline)
- Remove unnecessary uses of `tslint:disable-next-line`
- Remove unused arrow function parameter

Code cleanup per TSLint warnings

---

esm-samples/webpack/package.json
esm-samples/webpack/webpack.config.js

This PR fixes a number of errors with the webpack sample related to loading fonts, css and sourcemaps.

Fix errors in webpack sample

---

esm-samples/jsapi-angular-cli/README.md
esm-samples/jsapi-angular-cli/angular.json

Updates related to `buildOptimizer` setting change.

Update angular esm-sample

---

.prettierrc.json
esm-samples/rollup/README.md
esm-samples/rollup/package.json
esm-samples/rollup/rollup.config.js
esm-samples/rollup/src/main.js
esm-samples/webpack/README.md

* Fixed bug in main.js code by replacing main.js with the same code used in the webpack sample. Will address the bug in the other code separately.
* Updated rollup.config.js to handle copying assets, similar to the functionality in webpack.config.js
* Closes #275

ESM: Update rollup sample

---

esm-samples/jsapi-angular-cli/README.md
esm-samples/jsapi-angular-cli/src/app/app.component.ts

Updates to Angular sample:
* Add info to README about `unhandled promise rejections`.
* Change assetsPath to a relative path

Update Angular sample

---

esm-samples/README.md

* Update wording
* Clarify that type defs are included

Update esm-samples README

---

esm-samples/rollup/rollup.config.js

Related to: https://github.com/Esri/jsapi-resources/issues/325

Fix rollup sample live reload

---

esm-samples/jsapi-create-react-app/README.md
esm-samples/jsapi-create-react-app/package.json

update CRA browserslist and readme

update browserslist and readme

---

esm-samples/jsapi-angular-cli/README.md

Update known dependencies with recommendations towards upgrading to Angular 13. 
cc @odoe

Angular sample - update known dependencies for version 13

---

esm-samples/README.md

* General cleanup
* Add info about bundle size
cc @bsvensson

Update ESM samples top-level readme

---

esm-samples/.metrics/4.22.2.csv
esm-samples/jsapi-angular-cli/package.json

Test-only. 
@bsvensson @dasa @odoe @benelan @banuelosj

Build test 1

---

.github/scripts/analyze-builds.js
.github/scripts/build-size.js
esm-samples/.metrics/4.22.2.csv

- log all of stdout and stderr to the console
- Emphasis the step sections so things are easy to find 💅

ci: log stdout and stderr in metrics scripts

---

.github/scripts/README.md

@andygup and @banuelosj - let me know if the doc makes sense or needs any additional detail. You'll probably need to understand it in order to integrate the puppeteer part.

docs(ci): add readme for sample metrics scripts

---

esm-samples/jsapi-create-react-app/README.md
esm-samples/jsapi-create-react-app/package.json
esm-samples/jsapi-create-react-app/src/index.css
esm-samples/rollup/README.md
esm-samples/rollup/package.json
esm-samples/rollup/public/index.html
esm-samples/webpack/README.md
esm-samples/webpack/package.json
esm-samples/webpack/src/index.css

- Updated deps with `ncu -u`
- Installed `@arcgis/core@next`
- Tested with `npm start` and the dist from `npm run build`
- Bumped the CDN and npm package to `4.23`

chore(react, rollup, webpack): bump samples to 4.23

---

.github/workflows/analyze-builds.yml

Do not run metrics on PRs from dependabot

ci(metrics): ignore dependabot PRs

---

.github/scripts/README.md
README.md
esm-samples/README.md

* Updates to the analysis script READMEs.
* Includes caveats on performance analysis.
* Updates the repo copyright.
cc @dasa @odoe

README updates

---

3.x/bower/dojo/.bowerrc
3.x/bower/dojo/bower.json

This updates the 3x bower builds. We still have a couple of users that could use these updates as a reference.

update 3x bower

---

.github/scripts/analyze-builds.js
esm-samples/.metrics/4.24.0.csv

Fixes the header in 4.24.0.csv.
Also fixes the code that broke the CSV.

Fix broken CSV

---

.github/ISSUE_TEMPLATE/esm-report.md

This PR adds clarifications, as well as some reorganization.
I also updated many of the version number examples to get them close(r) to the latest releases.

Add clarification to ESM issue template about requiring repro cases

---

.github/workflows/stale.yml

Notes:
* Updated actions/stale from v4 to v5
* Draft-mode - debug-only: true

Add stale issue checker

---

4.x/typescript/Recenter/README.md
4.x/typescript/Recenter/index.html
4.x/typescript/Recenter/package.json
4.x/typescript/Recenter/tsconfig.json

Also used `prettier` to cleanup the formatting.

Update to 4.24 and don't use `tslib` from the CDN

---

4.x/typescript/README.md

Updated min version from 2.7 to 3.7 in AMD TS sample.

Update minimum TypeScript version

---

esm-samples/jsapi-custom-workers/src/index.js
esm-samples/jsapi-custom-workers/src/spatial-join-worker.js

Update custom worker sample to avoid clone(). Should be more efficient.

Update Custom Worker Sample

---

.github/scripts/package.json
.github/workflows/analyze-builds.yml

* Update github action to address Node 12 deprecation warning.
* Update github action deps.
@odoe can you sanity check this?

Updates to esm github action

---

esm-samples/jsapi-custom-widget/src/App.jsx
esm-samples/jsapi-custom-widget/src/CenterWidget.jsx

Just updated the `useEffect` dependency arrays, and added a cleanup method for `reactiveUtils` watch handle.

chore(custom-widget): add deps to useEffect arrays, add cleanup method for handle

---

esm-samples/jsapi-custom-ui/src/center-component.css

Class names did not match.
Reference: https://github.com/Esri/jsapi-resources/issues/482

fix(jsapi-custom-ui): update css className

---

esm-samples/jsapi-angular-cli/README.md

Reference: https://github.com/Esri/calcite-design-system/issues/7729, https://github.com/Esri/jsapi-resources/issues/481

docs(jsapi-angular-cli): add known issue for a calcite bug

---

CONTRIBUTING.md
README.md

This PR updates the main README and CONTRIBUTING files:
* Reorganize and reword
* Include a TOC for the ESM samples
* Make section headers more descriptive
* Add additional context and clarifications, where needed
/cc @bsvensson

chore: update README and CONTRIBUTING

---

esm-samples/jsapi-angular-cli/README.md

Clarifying the steps so we can reference them.
/cc @odoe

docs(Angular): clarify steps to disable zone.js click events

---

esm-samples/.metrics/4.28.0.csv
esm-samples/webpack/package.json
esm-samples/webpack/webpack.config.js

Adding TerserPlugin to remove comments.

chore(webpack): add terser-webpack-plugin

---

esm-samples/.metrics/4.28.0.csv
esm-samples/webpack/package.json

Update webpack ESM sample to `5.90.0`.
/cc @odoe

chore(webpack): update deps

---

esm-samples/webpack/src/index.css

Minor bump. Looks like I missed updating this.

chore(webpack): update index.css

---

.github/workflows/analyze-builds.yml

Update to handle upcoming directory re-naming for the core ESM samples.
/cc @manugadde @omarkawach

chore(GHA): update with new pathnames

---

core-samples/jsapi-esm-cdn/README.md
core-samples/jsapi-esm-cdn/esm-cdn.html

Update the sample to use the `importmap` pattern for better coding aesthetics.

chore(ESM CDN): update to use importmap

---

component-samples/map-components/tutorials/create-a-web-app-using-components-initial/package.json
component-samples/map-components/tutorials/create-a-web-app-using-components-solution/main.js
component-samples/map-components/tutorials/create-a-web-app-using-components-solution/package.json

This PR updates dependencies for the create a web app with components tutorial for the 4.31 release

chore(deps): update

---

.github/scripts/create-zips.js
.github/workflows/analyze-builds.yml

@omarkawach do we need to add any others?

chore(GHA - zip file create): add two new sample directories

---

intellisense.md

chore: fix broken links
